### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by bertvv** [andrewrothstein/ansible-dotnet#3]
Thank you for this useful role!

Is it possible to add some documentation on how to initialize the required role variables? It is currently not clear how `dotnet_subdirs` and `dotnet_checksum` should be initialized. Thanks!

**Comment by andrewrothstein** [comment]
I derive this role in two others. [dotnet-runtime](https://github.com/andrewrothstein/ansible-dotnet-runtime) and [dotnet-sdk](https://github.com/andrewrothstein/ansible-dotnet-sdk). that’s where I curate the checksums/subdirs.
